version: '3.8'
services:
  mysql:
    image: mariadb:10.6
    env_file: env/db.env
    volumes:
      - misp_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: misp
      MYSQL_USER: misp
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_password
    networks:
      - misp-net
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    command: ["redis-server", "--port", "6379"]
    volumes:
      - misp_redis:/data
    networks:
      - misp-net
    restart: unless-stopped

  misp:
    image: harvarditsecurity/misp:latest
    env_file: env/misp.env
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:80"
    volumes:
      - misp_data:/var/www/MISP
      - misp_logs:/var/www/MISP/app/tmp/logs
    networks:
      - misp-net
    restart: unless-stopped

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_password:
    file: ./secrets/mysql_password.txt

volumes:
  misp_db:
  misp_redis:
  misp_data:
  misp_logs:

networks:
  misp-net:
    driver: bridge
